# Generated by Django 5.0.1 on 2024-03-25 20:49

import customer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'City must be at least 5 characters'), customer.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'State must be at least 5 characters'), customer.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10, 'Street address must be at least 10 characters'), customer.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5, 'Zip code must be at least 5 characters'), customer.models.validate_non_empty]),
        ),
    ]
