# Generated by Django 5.0.1 on 2024-02-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_alter_cart_user_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
