# Generated by Django 5.0.1 on 2024-03-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cartapp.coupons'),
        ),
        migrations.AlterField(
            model_name='usercoupons',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_by', to='cartapp.coupons'),
        ),
        migrations.AlterField(
            model_name='usercoupons',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
