# Generated by Django 5.0.1 on 2024-03-26 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_alter_coupons_coupon_code_alter_coupons_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'ordering': ('coupon_code',), 'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
        migrations.AddField(
            model_name='coupons',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
