# Generated by Django 5.0.1 on 2024-02-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, upload_to='product'),
        ),
    ]
