# Generated by Django 5.0.1 on 2024-04-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-updated',), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
