# Generated by Django 5.0.1 on 2024-03-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Cash On Delivery', 'Cash On Delivery'), ('Wallet', 'Wallet')], default='Cash On Delivery', max_length=100),
        ),
    ]
