# Generated by Django 5.0.1 on 2024-03-25 20:51

import django.core.validators
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(10, 'Delivery address must be at least 10 characters'), shop.models.validate_non_empty]),
        ),
    ]
